Increase ci stability by caching artifacts

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -27,15 +27,21 @@ jobs:
         env:
           HAB_ORIGIN: biome
           HAB_AUTH_TOKEN: ${{ secrets.HAB_AUTH_TOKEN }}
-          HAB_STUDIO_SECRET_HAB_BDLR_CHANNEL: LTS-2024
+          HAB_STUDIO_SECRET_HAB_BLDR_CHANNEL: LTS-2024
         run: |
-          bio studio run 'make -f ci/Makefile setup'
+           for i in {1..3}; do
+             bio studio run 'make -f ci/Makefile setup' && success=true && break || sleep 10
+           done
+           if [ "$success" != "true" ]; then
+             echo "Failed to setup studio"
+             exit 1
+           fi
 
       - name: Build and Package
         env:
           HAB_ORIGIN: biome
           HAB_AUTH_TOKEN: ${{ secrets.HAB_AUTH_TOKEN }}
-          HAB_STUDIO_SECRET_HAB_BDLR_CHANNEL: LTS-2024
+          HAB_STUDIO_SECRET_HAB_BLDR_CHANNEL: LTS-2024
         run: |
           bio studio run 'make -f ci/Makefile all dist upload'
 
